config/routes.rb
Rails.application.routes.draw do
 
  
  resources :gallery_images
  resources :images
  resources :galleries
  #get 'sessions/new'
  #get 'users/new'

  root 'application#index'
  get 'about'      => 'static_pages#about'
  get 'news'       => 'static_pages#news'
  
  get    'signup'  => 'users#new'
  post 'signup'    => 'users#create'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :contacts
  resources :memberships
  resources :gym_classes
  resources :bookings
  resources :pages
  # You can have the root of your site routed with "root"
  # root 'application#hello'
  # end
  
end

app/models/membership.rb
class Membership < ApplicationRecord
    
    has_many :users, :foreign_key => "member_type"
    
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership,         only: [:show, :edit, :update, :destroy]
  #before_action :administrator_user,  only: [:index, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
   # @membership = Membership.find(params[:id])
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:title, :description, :price)
    end
    
    # Confirms an admin user.
    #def administrator_user
    #  redirect_to(root_url) unless current_user.administrator?
    #end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(membership) do |f| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table class=" table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    
  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.title %></td>
        <td><%= membership.description %></td>
        <td><%= membership.price %></td>
        <% if current_user %>
        <td><%= link_to 'Select Membership', edit_user_path(current_user) , class: "btn btn-lg btn-success" %></td>
        <% end %>
        <% if current_user && current_user.administrator? %>
        <td><%= link_to 'Edit', edit_membership_path(membership), class: "btn btn-lg btn-warning" %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %></td>
        <% else %>
        <td><%= link_to 'Show', membership, class: "btn btn-lg btn-info" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.administrator? %>
<%= link_to 'New Membership type', new_membership_path, class: "btn btn-lg btn-primary" %>
<% end %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @membership.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @membership.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @membership.price %>
</p>

<%= link_to 'Back', memberships_path %>