config/routes.rb
Rails.application.routes.draw do
 
  
  resources :gallery_images
  resources :images
  resources :galleries
  #get 'sessions/new'
  #get 'users/new'

  root 'application#index'
  get 'about'      => 'static_pages#about'
  get 'news'       => 'static_pages#news'
  
  get    'signup'  => 'users#new'
  post 'signup'    => 'users#create'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :contacts
  resources :memberships
  resources :gym_classes
  resources :bookings
  resources :pages
  # You can have the root of your site routed with "root"
  # root 'application#hello'
  # end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    
    belongs_to  :user, class_name: "User"
    belongs_to  :gym_classes, class_name: "GymClass"
    
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  validates_uniqueness_of :page_id
  belongs_to :page
  has_many :gallery_images, dependent: :destroy, foreign_key: :galleries_id
  has_many :images, :through => :gallery_images
end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
  belongs_to :gallery
  belongs_to :image
end

app/models/gym_class.rb
class GymClass < ApplicationRecord
    

    has_many :bookings, :foreign_key => "class_no",
                        dependent:   :destroy
    
end

app/models/image.rb
class Image < ApplicationRecord
    
    mount_uploader :filename, ImageUploader
    
    has_many :gallery_images, dependent: :destroy, foreign_key: :images_id
    has_many :galleries, :through => :gallery_images
end

app/models/membership.rb
class Membership < ApplicationRecord
    
    has_many :users, :foreign_key => "member_type"
    
end

app/models/page.rb
class Page < ApplicationRecord
  validates_uniqueness_of :permalink
  mount_uploader :image, ImageUploader
  
  has_one :gallery
  
  def to_param
    permalink
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  attr_accessor :remember_token
  
  has_many :bookings, :foreign_key => "membership_no", dependent:   :destroy
    
    
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    
    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
    # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  
    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
end

app/controllers/gym_classes_controller.rb
class GymClassesController < ApplicationController
  before_action :set_gym_class, only: [:show, :edit, :update, :destroy]

  # GET /gym_classes
  # GET /gym_classes.json
  def index
    @gym_classes = GymClass.all
  end

  # GET /gym_classes/1
  # GET /gym_classes/1.json
  def show
  end

  # GET /gym_classes/new
  def new
    @gym_class = GymClass.new
  end

  # GET /gym_classes/1/edit
  def edit
  end

  # POST /gym_classes
  # POST /gym_classes.json
  def create
    @gym_class = GymClass.new(gym_class_params)

    respond_to do |format|
      if @gym_class.save
        format.html { redirect_to @gym_class, notice: 'Gym class was successfully created.' }
        format.json { render :show, status: :created, location: @gym_class }
      else
        format.html { render :new }
        format.json { render json: @gym_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gym_classes/1
  # PATCH/PUT /gym_classes/1.json
  def update
    respond_to do |format|
      if @gym_class.update(gym_class_params)
        format.html { redirect_to @gym_class, notice: 'Gym class was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym_class }
      else
        format.html { render :edit }
        format.json { render json: @gym_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gym_classes/1
  # DELETE /gym_classes/1.json
  def destroy
    @gym_class.destroy
    respond_to do |format|
      format.html { redirect_to gym_classes_url, notice: 'Gym class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym_class
      @gym_class = GymClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_class_params
      params.require(:gym_class).permit(:name, :day, :time, :description, :instructor, :start_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # def nav_pages
  #   @nav_pages = Page.all
  # end
    
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "The GCD Gym"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gym_classes_helper.rb
module GymClassesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def administrator?
    has_role?(:administrator)
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
  
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  
  
end

app/views/gym_classes/_form.html.erb
<%= form_for(gym_class) do |f| %>
  <% if gym_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym_class.errors.count, "error") %> prohibited this gym_class from being saved:</h2>

      <ul>
      <% gym_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :day %>
    <%= f.text_field :day %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :instructor %>
    <%= f.text_field :instructor %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="actions">
    <%= f.submit "Create new Class", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/gym_classes/edit.html.erb
<h1>Editing Gym Class</h1>

<%= render 'form', gym_class: @gym_class %>

<%= link_to 'Show', @gym_class %> |
<%= link_to 'Back', gym_classes_path %>

app/views/gym_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gym Classes</h1>

<table class=" table table-striped">
  <thead>
    <tr>
      <th>Class Number</th>
      <th>Name</th>
      <th>Day</th>
      <th>Time</th>
      <th>Description</th>
      <th>Instructor</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gym_classes.each do |gym_class| %>
      <tr>
        <td><%= gym_class.id %></td>
        <td><%= gym_class.name %></td>
        <td><%= gym_class.day %></td>
        <td><%= gym_class.time %></td>
        <td><%= gym_class.description %></td>
        <td><%= gym_class.instructor %></td>
        <td><%= gym_class.start_date %></td>
        <td><%= link_to 'Register for Class', new_booking_path, class: "btn btn-lg btn-success" %></td>
        <% if current_user && current_user.administrator? %>
        <td><%= link_to 'Edit', edit_gym_class_path(gym_class), class: "btn btn-lg btn-warning" %></td>
        <td><%= link_to 'Destroy', gym_class, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %></td>
        <% else %>
        <td><%= link_to 'Show', gym_class, class: "btn btn-lg btn-info" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.administrator? %>
<%= link_to 'New Gym Class', new_gym_class_path, class: "btn btn-lg btn-primary" %>
<% end %>

app/views/gym_classes/new.html.erb
<h1>New Gym Class</h1>

<%= render 'form', gym_class: @gym_class %>

<%= link_to 'Back', gym_classes_path %>

app/views/gym_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gym_class.name %>
</p>

<p>
  <strong>Day:</strong>
  <%= @gym_class.day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @gym_class.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gym_class.description %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @gym_class.instructor %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @gym_class.start_date %>
</p>
<%= link_to 'Back', gym_classes_path %>