config/routes.rb
Rails.application.routes.draw do
 
  
  resources :gallery_images
  resources :images
  resources :galleries
  #get 'sessions/new'
  #get 'users/new'

  root 'application#index'
  get 'about'      => 'static_pages#about'
  get 'news'       => 'static_pages#news'
  
  get    'signup'  => 'users#new'
  post 'signup'    => 'users#create'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :contacts
  resources :memberships
  resources :gym_classes
  resources :bookings
  resources :pages
  # You can have the root of your site routed with "root"
  # root 'application#hello'
  # end
  
end

app/models/image.rb
class Image < ApplicationRecord
    
    mount_uploader :filename, ImageUploader
    
    has_many :gallery_images, dependent: :destroy, foreign_key: :images_id
    has_many :galleries, :through => :gallery_images
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename, :alt, :caption)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %>
    <%= f.file_field :filename, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :alt %>
    <%= f.text_field :alt, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :caption %>
    <%= f.text_field :caption, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image, class: "btn btn-primary" %>
<%= link_to 'Back', images_path, class: "btn btn-primary" %>

app/views/images/index.html.erb
<h1>Images</h1>

<table class=" table table-striped">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Alt</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.filename %></td>
        <td><%= image.alt %></td>
        <td><%= image.caption %></td>
        <td><%= link_to 'Show', image, class: "btn-sm btn-primary" %></td>
        <td><%= link_to 'Edit', edit_image_path(image), class: "btn-sm btn-warning" %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path, class: "btn btn-success" %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path, class: "btn-sm btn-primary" %>

app/views/images/show.html.erb
<p>
  <strong>Filename:</strong>
  <%= @image.filename %>
</p>

<p>
  <strong>Alt:</strong>
  <%= @image.alt %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @image.caption %>
</p>

<%= link_to 'Edit', edit_image_path(@image), class: "btn btn-warning" %>
<%= link_to 'Back', images_path, class: "btn btn-primary" %>