config/routes.rb
Rails.application.routes.draw do
 
  
  resources :gallery_images
  resources :images
  resources :galleries
  #get 'sessions/new'
  #get 'users/new'

  root 'application#index'
  get 'about'      => 'static_pages#about'
  get 'news'       => 'static_pages#news'
  
  get    'signup'  => 'users#new'
  post 'signup'    => 'users#create'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :contacts
  resources :memberships
  resources :gym_classes
  resources :bookings
  resources :pages
  # You can have the root of your site routed with "root"
  # root 'application#hello'
  # end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    
    belongs_to  :user, class_name: "User"
    belongs_to  :gym_classes, class_name: "GymClass"
    
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  validates_uniqueness_of :page_id
  belongs_to :page
  has_many :gallery_images, dependent: :destroy, foreign_key: :galleries_id
  has_many :images, :through => :gallery_images
end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
  belongs_to :gallery
  belongs_to :image
end

app/models/gym_class.rb
class GymClass < ApplicationRecord
    

    has_many :bookings, :foreign_key => "class_no",
                        dependent:   :destroy
    
end

app/models/image.rb
class Image < ApplicationRecord
    
    mount_uploader :filename, ImageUploader
    
    has_many :gallery_images, dependent: :destroy, foreign_key: :images_id
    has_many :galleries, :through => :gallery_images
end

app/models/membership.rb
class Membership < ApplicationRecord
    
    has_many :users, :foreign_key => "member_type"
    
end

app/models/page.rb
class Page < ApplicationRecord
  validates_uniqueness_of :permalink
  mount_uploader :image, ImageUploader
  
  has_one :gallery
  
  def to_param
    permalink
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  attr_accessor :remember_token
  
  has_many :bookings, :foreign_key => "membership_no", dependent:   :destroy
    
    
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    
    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
    # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  
    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # def nav_pages
  #   @nav_pages = Page.all
  # end
    
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "The GCD Gym"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gym_classes_helper.rb
module GymClassesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def administrator?
    has_role?(:administrator)
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
  
  
  
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  
  
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="clear: both;">
  <br/><br/>
  <small>
    The Griffith College Gym
    by Gareth O'Connor | Shane Forbes
  </small>
  <nav>
    
    <ul>
      <% @pages.each do |page| %>
        <li><%= link_to page.name.humanize, page %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "the Griffith College Gym", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user && current_user.administrator? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Administration <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Manage", '#' %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Web Pages", pages_path %></li>
                  <li><%= link_to "Image Galleries", galleries_path %></li>
                  <li><%= link_to "Messages", contacts_path %></li>
                  <li><%= link_to "Users", users_path %></li>
                  <li><%= link_to "Memberships", page_path("memberships") %></li>
                  <li><%= link_to "Classes", page_path("classes") %></li>
                  <li><%= link_to "Bookings", bookings_path %></li>
                </ul>
              </li>
            <% end %>
            <% @pages.each do |page| %>
              <li><%= link_to page.name.humanize, page %></li>
            <% end %>
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>